### ISSUE TITLE
Can't find later-cov.js?

### ISSUE THREAD

**Issue by flipace** [bunkat/later#155]
For some reason i get an error that later-cov.js couldn't be found.
I checked the source code and it seems like this file has been explicitly ignored for git.

I didn't set the env LATER_COV to anything - so I guess that webpack tries to include both - the later.js and later-cov.js in a bundle?

I tried to set process.env.LATER_COV to false but the error kept popping up.

Any help would be greatly appreciated.

**Comment by bunkat** [comment]
I don't use the library with webpack and so I'm not sure what it is trying to do.  If you modify index.js to only point to later.js does it work?

**Comment by flipace** [comment]
Yes, that way it works, but this is not a solution i can stick with. I wonder why this is still in the repo, since this file later-cov.js simply does not exist..

**Comment by bunkat** [comment]
The file exists when you produce coverage builds. I have no idea why webpack is trying to load it, but the fact that removing it works lets me know that it is in fact the problem.  Next time I update I'll change the way that I do coverage builds I guess.

**Comment by TimNZ** [comment]
I expect webpack is confused by this in index.js

```
require(process.env['LATER_COV'] ? "./later-cov" : "./later");
```

Having a quick look at Webpack docs I can't see anything obvious to support an env check.

**Comment by rotemtam** [comment]
Here's a way around it:

```bash 
npm i --save-dev string-replace-loader
```

In your webpack config:

```js
module.exports = {
// ...
loaders: [
      {
        test: /later\/index.js$/,
        loader: 'string-replace',
        query: {
          search: `later-cov`,
          replace: 'later'
        }
      }
    ]
// ..
}
```

**Comment by icfantv** [comment]
@bunkat have you decided on a fix here?

**Comment by icfantv** [comment]
The big thing I notice here is that in the NPM distribution of later, there is no `later-cov.js` file so even if people aren't sure about why the environment variable is being set, there's no file to load even it if _was_ set...

**Comment by icfantv** [comment]
@rotemtam that solution no longer works in Webpack 2 as it will build, but the runtime code will still have the original code from `index.js` present and it will complain about `process` not being defined.

**Comment by rotemtam** [comment]
@icfantv sorry to hear! I haven't upgraded to webpack2 yet, so I can't offer a solution, sorry

**Comment by rex** [comment]
@icfantv @rotemtam Are you guys saying that I can't use `later` if I am using webpack to build the frontend assets? If so, that is extremely disappointing, since my team and I just found this library and realized it solves most - if not all - of our problems.

**Comment by icfantv** [comment]
@rex, it's MIT license so we just pulled it in to our own repo.  Problem solved.

**Comment by rex** [comment]
@icfantv Makes sense :) I reached out to @bunkat in hopes that my team and I can become maintainers so we can do this in a more official capacity. 🤞

**Comment by appinteractive** [comment]
any progress on that issue?

**Comment by RickCarlino** [comment]
I removed the problem line in a fork [here](https://github.com/RickCarlino/later) until a permanent solution comes about.

You can add it to your `package.json` as:

```
"later": "RickCarlino/later",
```

Just tested it and appears to work with WebPack 2.

**Comment by eburi** [comment]
There is an easy workaround: 

require('later/later.js');

**Comment by TimNZ** [comment]
@eburi : Love a so simple duh! answer.

**Comment by Velocitas1** [comment]
@rotemtam I was able to use your suggestion with a slight variation that still works in Webpack 2:
`
			{
				test: /later\/index.js$/,
				loader: "string-replace-loader",
				options: {
					search: `process.env['LATER_COV'] ? "./later-cov" : `,
					replace: ""
				}
			},
`

**Comment by eburi** [comment]
As mentioned before, you can just require the file that works (later/later.js).
If you want to keep your code 'clean' of such workarounds, in webpack 2 you can also define an 'alias' under 'resolve':
alias:{
  later: "later/later.js"
}
 
and then just: require('later');


Maybe that's an other duh! answer, but I don't understand why anybody would go to such extends as to use a string-replace-loader.... or even integrate the whole source into the project...

npm-packages with issues like that are IMHO daily business, deal with and profit!

**Comment by warpdesign** [comment]
I am having the problem too.

For some explanation I think when dynamic require/imports are encoutered, webpack has to build dependency graph for each case, that's why it attempts to load the load-cov file and attempt to see if there are more dependencies although it wouldn't be used in the browser.

The alias tip fixes the problem.

**Comment by sondretjvimond** [comment]
The alias solution does not work with Webpack 3 it seems. Neither does require or import later/later.js. @RickCarlino 's fork works though.

**Comment by Oceanswave** [comment]
Came across this issue this evening, using create-react-app so ejecting to add in an webpack alias is prohibitive. @RickCarlino's fork worked great.

**Comment by cjessett** [comment]
Using [`webpack.DefinePlugin`](https://webpack.js.org/plugins/define-plugin/) worked for me. 
```
  plugins: [
    new webpack.DefinePlugin({ 'process.env': { LATER_COV: false } }),
  ],
```

**Comment by moribellamy** [comment]
+1 on this.

Couldn't use @cjessett's suggestion b/c of create-react-app, and i'm afraid to eject or to hack around the default config.

@RickCarlino's suggestion worked for me.

**Comment by kiddailey** [comment]
@cjessett Thank you for mentioning the DefinePlugin solution. Just wanted to reply to let anyone else reading this thread -- that solution worked great for getting later to work with webpack and electron-builder (and on all platforms consistently for dev and production) when none of the other solutions would.

Edit: It's worth noting though that this will wipe out everything else in process.env, so it may make more sense, depending on your needs, to use webpack's EnvironmentPlugin, which simply adds this new environment variable:

```
plugins: [
    new webpack.EnvironmentPlugin({
      LATER_COV: false
    })
],
```

https://webpack.js.org/plugins/environment-plugin/

**Comment by icarter09** [comment]
Just ran into this problem today and using @RickCarlino's suggestion worked for me.

**Comment by revolunet** [comment]
FYI this makes it impossible to use `later` in codesandbox.io :/

**Comment by niftylettuce** [comment]
This issue is now fixed per my work with **[Bree](https://github.com/breejs/bree)**, I have an updated fork of this package called `@breejs/later`.  See https://github.com/breejs/later if you have additional PR's or issues to file.  Contributions welcome to clean it up.

**Comment by kostikovk** [comment]
@vue/cli 4.5.9

> **It's help me**

`
chainWebpack: cfg => {
    cfg.plugin('define').tap(args => {
      args[0] = {
        ...args[0],
        'process.env': { LATER_COV: false }
      }
      return args
    })
`

**Comment by egeersoz** [comment]
Pretty crazy that this five year old bug still exists. :)

Is this repo abandoned or something?

edit: oh duh, just saw the message on the readme.

**Comment by tirumalavasu-modak** [comment]
How can I do this in vite config. Any help?

**Comment by andrzejkaras** [comment]
> How can I do this in vite config. Any help?

I am having the same problem. Anybody could help?
